# -*- coding: utf-8 -*-
"""test_video

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bweEDCHUOI24QBYYk7J4L_-NfzLrD6nK
"""

def test_video():
  assert(10 + 10 == 20)