name: run_all_tests

on: [push, pull_request, workflow_dispatch]

jobs:
  RunAllTests:
    runs-on: ubuntu-20.04
    container: python:3.8.1
    steps:
      - uses: actions/checkout@v2
      - name: run_all_tests
        run: |
          apt-get update
          apt-get install ffmpeg libsm6 libxext6  -y
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          python -m pytest